### ISSUE TITLE
[SOLVED] Error 403 Forbidden

### ISSUE THREAD

**Issue by bonnebulle** [immanuelfodor/shaarli-custom-css#1]
Hello
Thanks for all your plugins here !
Am working on a version for studens and I realy want they can edit there css...
But the .htaccess give me this 403 error (if I comment it, it'work !)
So maybe you have some tricks to help me ?
I just download the last version of your plugin (last version)
Have a nice day !

**Comment by immanuelfodor** [comment]
Hi, thanks for the kind words! 

Yes, there is an open issue for this in the main Shaarli repo: https://github.com/shaarli/Shaarli/issues/1667

Since I use Shaarli dockerized, and it's based on nginx, there is no relevance of the htaccess files, so I can access the CSS file from the data folder just fine. Modifying the htaccess to allow the custom_css.css file besides the user.css seems to be a workaround as well as using the Docker image with plugins encapsulated: https://github.com/shaarli/Shaarli/issues/1372#issuecomment-546341830

**Comment by immanuelfodor** [comment]
The solution is to modify the `custom_css/custom_css.php` on the following two lines:

Line 33:
```diff
 */
function hook_custom_css_render_includes($data, $conf)
{
-   $customCss = $conf->get('resource.data_dir') . '/custom_css.css';
+   $customCss = $conf->get('resource.data_dir') . '/user.css';

    if (file_exists($customCss)) {
        $data['css_files'][] = $customCss;
```
Line 60:
```diff
       $customCss = $data['CUSTOM_CSS'];
    }

-   file_put_contents($conf->get('resource.data_dir') . '/custom_css.css', $customCss);
+   file_put_contents($conf->get('resource.data_dir') . '/user.css', $customCss);

    return $data;
}
```

This change moves the custom CSS from `data/custom_css.css` to `data/user.css` that is whitelisted in Shaarli's default htaccess. Please note that the file contents are overwritten if you already have such a file in place. 

Nginx and docker users are not impacted as there are no relevance of the htaccess file, just for Apache.
